### PR TITLE
upgrade dependencies

### PR DESCRIPTION
**Pull request by alvarezfr**
# Introduction
Hi @peter-murray,

I'm loving using this action, thank you for it. 

I just create this PR to upgrade the dependencies, because of this warning: 
```shell
# npm audit report:
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix`
node_modules/node-fetch

1 high severity vulnerability

To address all issues, run:
  npm audit fix
```
# What I did?
I just ran the following commands to upgrade the dependencies:

## npm outdated
```shell
$ npm outdated
Package          Current  Wanted  Latest  Location                      Depended by
@actions/core      1.2.6   1.8.2   1.8.2  node_modules/@actions/core    issue-body-parser-action
@actions/github    2.2.0   2.2.0   5.0.3  node_modules/@actions/github  issue-body-parser-action
yaml              1.10.0  1.10.2   2.1.1  node_modules/yaml             issue-body-parser-action
```

## npm audit
```shell
$ npm audit
# npm audit report

node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix`
node_modules/node-fetch

1 high severity vulnerability

To address all issues, run:
  npm audit fix
```

## npm upgrade
```shell
$ npm upgrade
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

added 3 packages, removed 1 package, changed 29 packages, and audited 61 packages in 2s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

## npm outdated
```shell
$ npm outdated
Package          Current  Wanted  Latest  Location                      Depended by
@actions/github    2.2.0   2.2.0   5.0.3  node_modules/@actions/github  issue-body-parser-action
yaml              1.10.2  1.10.2   2.1.1  node_modules/yaml             issue-body-parser-action
```

## npm audit
```shell
$ npm audit
found 0 vulnerabilities
```

# Testing

After running the commands, just created the build and tested it with the workflow_dispatch.

You can check the output of the tests here: 
- json: https://github.com/alvarezfr/issue-body-parser-action/runs/6791883820?check_suite_focus=true
- yaml: https://github.com/alvarezfr/issue-body-parser-action/runs/6791884655?check_suite_focus=true

The output looks good to me. It just doesn't return the id key, but it is not in the issue body, so I think it should have another purpose.

Thanks for your time.

### CODE REVIEW

**Comment by peter-murray** [comment]
Thank you for this, but it appears to be missing the actual change to the `package.json` file, can you also add that to this branch?

**Comment by alvarezfr** [comment]
Hi @peter-murray.

I don't mind to make the changes if needed, but I'm not sure to understand your request. Do you mean dependencies list in the package.json?

Those configurations still being valid, I just upgraded the versions of the package-lock.json following the rules that you have defined in the package.json. I mean, using the `npm outdated` commands that I pasted in the PR to explain this:

**Before the upgrade:** 
```shell
$ npm outdated
Package          Current  Wanted  Latest  Location                      Depended by
@actions/core      1.2.6   1.8.2   1.8.2  node_modules/@actions/core    issue-body-parser-action
@actions/github    2.2.0   2.2.0   5.0.3  node_modules/@actions/github  issue-body-parser-action
yaml              1.10.0  1.10.2   2.1.1  node_modules/yaml             issue-body-parser-action
```
**After the upgrade:**
```shell
$ npm outdated
Package          Current  Wanted  Latest  Location                      Depended by
@actions/github    2.2.0   2.2.0   5.0.3  node_modules/@actions/github  issue-body-parser-action
yaml              1.10.2  1.10.2   2.1.1  node_modules/yaml             issue-body-parser-action
```

As an example, if you see what happened with the package `yaml`, it was in the version `1.10.0` at first. With the upgrade, it changes to version `1.10.2` but still showing that it is not fully upgraded as it latest version is `2.1.1`.  

This is because the dependency lock that you had already defined, which for the case of yaml is `"yaml": "^1.10.0"`. What that means in this case is npm will upgrade yaml that match the rule 'version >= 1.10.0 && version < 2.0.0' ([more information here](https://github.com/npm/node-semver#caret-ranges-123-025-004)). So, due to the current configuration of the package.json some of the packages has not been upgraded to the latest available version, and also due to this the dependencies list in the package.json doesn't need to be updated.

What do you think? Is that what you mean? 

BR.

**Comment by peter-murray** [comment]
Yes, thanks I understand that, but I prefer personally to also bump up the package.json file to match the version as the lowest match of what we are moving to, that way if someone removed the lock file (I have worked with developers that do this in the past) then it would not fetch an older version if they are referencing a proxy/mirror that is out of date.

I also tend to lean in on reading the `package.json` file myself as to which direct dependencies and versions are "current".

**Comment by alvarezfr** [comment]
Understood. I updated the `package.json` file.

Also, I have upgraded the @github/core to the latest version as it was outdated based on the rules in the package.json.

The test looks fine:
https://github.com/alvarezfr/issue-body-parser-action/runs/7131255024?check_suite_focus=true
https://github.com/alvarezfr/issue-body-parser-action/runs/7131257022?check_suite_focus=true

BR.

**Comment by peter-murray** [comment]
Thank you 🙇 @alvarezfr for your contribution.

**Pull request merged**
